### ISSUE TITLE
Last of the hangup tones is louder that the rest.

### ISSUE THREAD

**Issue by SaltyCybernaut** [ubports/dialer-app#62] opened 2019-02-19 06:10 UTC
After a call finishes the Dialer app will play three or four beeps to indicate that the call has ended. The very last beep is louder than the rest and can bother people around you. This problem is most likely related to the fact the the Dialer will increase the volume (equivalent to 'speaker phone' levels) so that DTMF tones can be heard when the app opens or when it returns to the screen displaying the digits 0-9. The fix requiring the least amount of effort would be to delay increasing the volume until all beeps are finished.

**Comment by cibersheep** [comment] 2020-10-27 02:52
Is this the same as https://github.com/ubports/dialer-app/issues/59 ?

**Comment by lduboeuf** [comment] 2020-10-27 07:25
yes true, duplicate off #59

**Closed as completed by lduboeuf** 2020-10-27 07:25 UTC
