### ISSUE TITLE
Interface got stucked during a call

### ISSUE THREAD

**Issue by j2g2rp** [ubports/dialer-app#175] opened 2021-12-26 10:40 UTC
Sometimes during a call the interface of the app got stucked, it doesn't allow you to stop the call.

Device Vollaphone X.
Channel RC
Update: 2021-W51/2

I don't know if the log can be usefull: The steps that I had done when I noticed the bug were:
Open the app--> search on recent calls-->select a contact--> dial to the selected number--> put the speakers--> try to stop the call (the interface was stucked)--> close the app
![imagen](https://user-images.githubusercontent.com/28528967/147405540-19a6f829-7171-475b-8f82-6195c5b4231b.png)

**Comment by ivoxavier** [comment] 2021-12-27 10:05
Hi,

I can confirm this on OnePlus 6T (OTA-20) as well.

**Comment by lduboeuf** [comment] 2022-01-10 20:37
@j2g2rp @ivoxavier still occurring ?
Is it the same as https://github.com/ubports/ubuntu-touch/issues/195 ?

**Comment by j2g2rp** [comment] 2022-01-10 21:46
I don't use calls too often so I can't say if it isn't happening now...
Maybe is the same issue, yes. Sorry. At least it is the same behavior when you try to hang a call.

**Comment by ivoxavier** [comment] 2022-01-11 09:39
@lduboeuf Hi, yes even yesterday I had this issue. I had got a call, take it and then the person on the otherside did not stopped the call and could not end the call on my side as well because the UI was stucked. Needed to reboot my phone in order to stop the call, but primarily to be possible to receive new calls.

**Comment by lduboeuf** [comment] 2022-01-11 09:42
Well idk, but not a dialer-app issue i would say. Maybe a porting issue ?

**Comment by ivoxavier** [comment] 2022-01-11 09:49
I'm using a H9 device. Idk if this is happening as well on older devices like n5 or fp2.

**Comment by j2g2rp** [comment] 2022-01-11 10:33
@lduboeuf I'm not sure. I asked the 26th of December in the QA group about this behavior and some people had the same problem so they suggested me to make a ticket. I assumed that there was a problem with dialer but I'm not sure if it could be related to H9 devices, Ofono or anything else. Do yo know if are something that we can do to track the problem next time we see that to check which is the origin of the problem?

Thank you in advance.

**Comment by lduboeuf** [comment] 2022-01-11 10:38
@j2g2rp If UI completely stuck, unity8.log should provide some info, but if reboot is mandatory, it will be in unity8.log.x.gz, maybe dbus.log too.
I don't have that issue on Xperia X ( Halium 7.1 iirc )

**Comment by j2g2rp** [comment] 2022-01-11 10:41
Just wonder, by UI you mean all the phone? That's not my case, I could close the app normally because unity8 were working fine.

**Comment by lduboeuf** [comment] 2022-01-11 10:45
i thought @ivoxavier reported completeUI freeze.
So not sure forunity8.log.  dbus.log should provide some info. We need to know if specific to H9 devices, in that case, there could be something wrong with ofono or somewhere i don't know

**Comment by ivoxavier** [comment] 2022-01-11 10:46
Yeah when saying UI stuck I wanted to mean = phone app stuck. Lomiri is still working. I only reboot to ensure no problems for the next call. Sorry for the misunderstanding

**Comment by Flohack74** [comment] 2022-01-11 15:28
In my opinion dialer does not get the signal that the call has been ended. Sounds like middleware problem / RIL signalling to ofono and state machine in ofono getting frozen in the wrong state maybe. Or telephony-service, hard to say

**Comment by j2g2rp** [comment] 2022-01-19 10:00
today it happened me again. During the call since I couldn't hangup the call I closed the app. The upper bar of lomiri turned to blue and showing the duration of the call as expected. I opened the dialer app through the unity bar, and then I could hangup correctly, here is the log of the app but I think that it wouldn't be useful...
![imagen](https://user-images.githubusercontent.com/28528967/150107339-c8fb91c0-ec16-46c8-bf30-c0d57b937c8c.png)

**Comment by lduboeuf** [comment] 2022-01-19 10:26
@j2g2rp 
So we see here before restarting the app that the  CallState never reach 5(CallStateActive) and is stuck on callState=3 (CallStateInitialised)
https://telepathy.freedesktop.org/doc/telepathy-qt/a06885.html#ga29b57a5b4f94c451af84b5e57102c4d9

But this doesn't help finding why :-| 
As it seems it depends on device , i suspect the issue on ofono and/or Modem

**Comment by peat-psuwit** [comment] 2022-11-24 16:20
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/development/core/dialer-app/-/issues/173

Sorry for your inconvenience.

**Closed as not planned by peat-psuwit** 2022-11-24 16:20 UTC
